export default actionsType = {

    // REDUX
    REDUX_ADD_NEW_TASK: 'REDUX_ADD_NEW_TASK',
    REDUX_DELETE_TASK: 'REDUX_DELETE_TASK',
    REDUX_FINISH_TASK: 'REDUX_FINISH_TASK',

    REDUX_INCREASE: 'REDUX_INCREASE',
    REDUX_DECREASE: 'REDUX_DECREASE',

    //SAGA
    SAGA_REQUEST_SUCCESS: 'SAGA_REQUEST_SUCCESS',
    SAGA_REQUEST_ERROR: 'SAGA_REQUEST_ERROR'

}
